# Generated by Django 5.1.2 on 2024-11-29 06:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('cnic', models.CharField(max_length=15, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='CNIC must be in the format XXXX-XXXXXXX-X', regex='^\\d{5}-\\d{7}-\\d{1}$')])),
                ('name', models.CharField(max_length=25)),
                ('contact', models.CharField(max_length=15)),
                ('license_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DriverStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=50)),
            ],
        ),
    ]
