# Generated by Django 5.1.2 on 2024-10-30 03:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('cnic', models.CharField(max_length=15, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='CNIC must be in the format XXXX-XXXXXXX-X', regex='^\\d{5}-\\d{7}-\\d{1}$')])),
                ('name', models.CharField(max_length=25)),
                ('contact', models.CharField(max_length=15)),
                ('license_number', models.CharField(max_length=50)),
                ('appointed_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='transport.transportprovider')),
                ('appointed_vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transport.vehicle')),
                ('registration_status', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='driver.driverstatus')),
            ],
        ),
    ]
