# Generated by Django 5.1.2 on 2024-12-02 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='registration_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='driver.driverstatus'),
        ),
    ]
