# Generated by Django 5.1.2 on 2024-10-30 03:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payment.paymentmethod'),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.paymentstatus'),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='payment.receipt'),
        ),
    ]
