# Generated by Django 5.1.2 on 2024-11-30 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('noticeboard', '0001_initial'),
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='userauth.appuser'),
        ),
    ]
