# Generated by Django 5.1.2 on 2024-12-01 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='rating',
        ),
    ]
