# Generated by Django 5.1.2 on 2024-11-29 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transport', '0001_initial'),
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportprovider',
            name='representative',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userauth.providerrepresentative'),
        ),
        migrations.AddField(
            model_name='route',
            name='appointed_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='transport.transportprovider'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='capacity_type',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.capacitytype'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='route_no',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transport.route'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='transport_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='transport.transportprovider'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.vehiclestatus'),
        ),
        migrations.AlterUniqueTogether(
            name='routestop',
            unique_together={('route', 'stop_order')},
        ),
    ]
