# Generated by Django 5.1.2 on 2024-11-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerrepresentative',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
