# Generated by Django 5.1.2 on 2024-11-29 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='nearest_landmark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.nearestlandmark'),
        ),
    ]
