# Generated by Django 5.1.2 on 2024-11-29 06:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderRepresentative',
            fields=[
                ('representative_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('representative_cnic', models.CharField(max_length=15, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='CNIC must be in the format XXXX-XXXXXXXX-X', regex='^\\d{5}-\\d{7}-\\d{1}$')])),
                ('representative_contact', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='transportprovider',
            name='representative',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transport.providerrepresentative'),
        ),
    ]
