# Generated by Django 5.1.2 on 2024-12-09 04:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='tracking_id',
            field=models.EmailField(max_length=254, validators=[django.core.validators.RegexValidator(message='Trakcing must be in the format cbt@route(number).com', regex='^cbt@route\\d{7}.com$')]),
        ),
    ]
