# Generated by Django 5.1.2 on 2024-11-27 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_alter_routestop_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportprovider',
            name='driver_contact_number',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AddField(
            model_name='transportprovider',
            name='driver_license_number',
            field=models.CharField(default=0, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transportprovider',
            name='vehicle_assigned',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_providers', to='transport.vehicle'),
            preserve_default=False,
        ),
    ]
