# Generated by Django 5.1.2 on 2024-11-29 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_alter_stop_nearest_landmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='end_stop',
        ),
    ]
