# Generated by Django 5.1.2 on 2024-11-29 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_remove_route_end_stop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='capacity_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.capacitytype'),
        ),
    ]
